export const surpriseMePrompts = [
    'Cat wearing crocs',
    'Cat working on a laptop',
    'Cat on moon',
    'Cat chasing a dragon',
    'Cat as an angel',
    'Cat wearing cowboy hat',
    'Cat as twitter ceo',
    'Cat surfing a massive wave',
    'Cat on moon',
    'Cat on people head',
    'Cat chasing a wolf pack',
    'Cat painting',
    'Water painting of cats',
    'Oil painting of cats',
    'Cat teaching physics',
    'Cat eating fruits',
    'Cat singing at concert',
    'Cat reading quran',
    'Cat giving sermon in a mosque on friday',
    'A gang of cats',
    'Cat as a superhero',
    'Cat praying during ramadan',
    'Cat mafias',
    'cat wearing headphones',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'an oil painting by Matisse of a Cat playing chess',
    "a macro 35mm photograph of two cats in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a Cat watching a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut cat lounging in a tropical resort in space, vaporwave',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a Cat in the style of Starry Night',
    'A comic book cover of a cat wearing headphones',
    'A Samurai Cat riding a Horse on Mars, lomography.',
    'A Cat standing in front of a stargate to another dimension',
    'A Cat working at a hotdog stand, lomography',
    'A Cat walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A Synthwave Cat, Blade Runner Cyberpunk',
    'An astronaut Cat encountering an alien life form on a distant planet, photography',
    'A Cat riding a Dinosaur exploring Cape Town, photography',
    'A Cat falling in Love with his Computer, digital art',
    'A photograph of a cat exploring Tokyo at night, lomography',
    'Cat walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A Cat wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Cat in a space Shuttle flying above Cape Town, digital art',
];
